spring:
  #数据源
  datasource:
    username: datax_admin1
    password: TWgWRaF6hOl5P2Z1cRXt
    url: jdbc:mysql://10.21.33.246:15060/datax_admin?serverTimezone=Asia/Shanghai&useLegacyDatetimeCode=false&useSSL=true&nullNamePatternMatchesAll=true&useUnicode=true&characterEncoding=UTF-8

# 配置mybatis-plus打印slq日志
logging:
  level:
    com.wugui.datax.admin.mapper: error
  path: /data/logs/datax-admin/

#datax-job, access token
datax:
  job:
    accessToken: A3Ecl05MWqBD1F
    i18n: zh
    ## triggerpool max size
    triggerpool:
      fast:
        max: 200
      slow:
        max: 100
      ### log retention days
    logretentiondays: 30